### PR TITLE
initial custom delimiter support

### PR DESCRIPTION
**Pull request by foi**
I have added _opts (delimeter) as chriswiggins (https://github.com/sebastianseilund/node-json-socket/pull/20) propose.

I have copy pasted all tests with add custom delimeter (maybe it is not best method).

P.S. It is my first PR

### CODE REVIEW

**Comment by SamuelBolduc** [comment]
Clean implementation, great test coverage. LGTM

@sebastianseilund you might want to have a look before we merge? It shouldn't impact anyone using the library as-is, so no major version bump, but still worth having a look.

**Comment by SamuelBolduc** [comment]
@foi maybe a suggestion, after having a second look at it : on `sendSingleMessage` and `sendSingleMessageAndReceive`, maybe the `opts` argument could be before `callback`? We could check if the fourth argument is a function or an object, and adjust accordingly?

**Comment by foi** [comment]
@SamuelBolduc, i was insert opts as last argument because backward compatibility. Insert opts before callback it's good idea, i will try do it.

**Comment by foi** [comment]
Done .I was add 4 tests, but i don't know how to test assert sendSingleMessageAndReceive in callback that incoming message (to client) is equal message what server sent.

**Comment by SamuelBolduc** [comment]
@foi you could call your `done()` callback inside the callback of `sendSingleMessageAndReceive()` maybe? Right now you call if in the server after it receives a `message` event. If add an `assert` in the callback of `sendSingleMessageAndReceive()` while keeping `assert` in the server `message` handler, it will ensure that both ends are tested. At the very end (in the `sendSingleMessageAndReceive()` callback, after your `assert`), you then call `done()`.

Would that work?

**Comment by foi** [comment]
@SamuelBolduc thanks for support! It was well done!

**Comment by SamuelBolduc** [comment]
@foi looks good, thank you for your contribution!

**Pull request merged**
